### ISSUE TITLE
Generalize the action to update any files

### ISSUE THREAD

**Issue by branoholy** [branoholy/update-files-action#30]
## Problem

The action is currently focused on lock files only. However, it should be easier to extend the functionality to update any files.

## Solution

Extend input arguments to support custom file paths and update commands. It will be necessary to commit multiple files at once.

New arguments could look like this
```yaml
uses: branoholy/update-files-action
with:
  token: ${{ secrets.GITHUB_TOKEN }}
  paths: 'path/to/file.txt, path/to/another/file.txt'
  commands: 'gen-command-1, gen-command-2'
  keep-paths: path/to/another/file.txt
```
where `paths` is a required comma-separated list of file paths, `commands` is a required comma-separated list of update commands, and `keep-paths` is an optional comma-separated list of file paths that won't be deleted before the commands are executed. The `keep-paths` input might be useful when the commands just update the files and don't generate them from scratch.

The following could be used to update the lock file of NPM
```yaml
uses: branoholy/update-files-action
with:
  token: ${{ secrets.GITHUB_TOKEN }}
  paths: package-lock.json
  commands: 'npm i'
```
