### ISSUE TITLE
Allow a custom base branch for the new branch

### ISSUE THREAD

**Issue by branoholy** [branoholy/update-files-action#846]
## Problem

It's not possible to specify the base branch for the newly creating branch.

## Solution

Add an argument to specify the base branch. Refactor arguments for branch operations.

```yaml
branch.name: default-branch
branch.base: default-branch
branch.recreate: false
```
